name: traceharbor-events

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.2.2
    command:
      - redpanda
      - start
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --rpc-addr=redpanda:33145
      - --advertise-rpc-addr=redpanda:33145
      - --mode=dev-container
      - --smp=1
      - --default-log-level=info
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    ports:
      - "127.0.0.1:19092:19092"
      - "127.0.0.1:19644:9644"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info", "-X", "brokers=redpanda:9092"]
      interval: 5s
      timeout: 5s
      retries: 10
    security_opt:
      - no-new-privileges:true

  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v26.2.2
    depends_on:
      redpanda:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-ec"]
    command:
      - >-
        rpk topic create traceharbor.orders.v1 --brokers redpanda:9092 --partitions 3
        || rpk topic describe traceharbor.orders.v1 --brokers redpanda:9092;
        rpk topic create traceharbor.orders.dlq.v1 --brokers redpanda:9092 --partitions 1
        || rpk topic describe traceharbor.orders.dlq.v1 --brokers redpanda:9092
    security_opt:
      - no-new-privileges:true

  console:
    image: docker.redpanda.com/redpandadata/console:v3.10.0
    depends_on:
      redpanda:
        condition: service_healthy
      topic-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports:
      - "127.0.0.1:8080:8080"
    security_opt:
      - no-new-privileges:true

volumes:
  redpanda-data:
